### ISSUE TITLE
Tracking all issues related to litgpt

### ISSUE THREAD

**Issue by siddharth9820** [hpcgroup/axonn#92]
- [x] Create an expert-mode model definition.
- [ ] Test pretraining in expert mode
- [ ] Test pretraining in non expert mode
- [x] Test finetuning in expert mode
- [x] Test finetuning in non expert mode
- [x] Test chat in expert mode
- [x] Test chat in non expert mode
- [x] Finetuning scripts are setup with a small batch size. We should try row tensor parallelism and show improvements over FSDP.
